import Head from "next/head";
import React from "react";

import Cards from "../components/cards";
import { CodeTag, Container, Description, Main, Title } from "../components/sharedstyles";

export default function Home() {
	return (
		<Container>
			<Head>
				<title>Create Next App</title>
				<meta content="Generated by create next app" name="description" />
				<link href="/favicon.ico" rel="icon" />
			</Head>
			<Main>
				<Title>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</Title>

				<Description>
					Get started by editing
					<CodeTag>pages/index.tsx</CodeTag>
				</Description>

				<Cards />
			</Main>
		</Container>
	);
}
